---
- name: Trek Buddy app
  hosts: all
  tasks: 
    - name: Stopping already running compose
      shell: docker-compose down
    - name: Remove already existing image
      docker_image: 
        name: shuddd/frontend
        state: absent
        force: yes
    - name: Pull updated image
      docker_image:
        name: shuddd/frontend
    - name: Copy docker compose file to host
      copy:
        src: docker-compose.yml
        dest: docker-compose.yml
    - name: Run docker compose
      shell: docker-compose up
